cmd_/usr/src/linux-headers-5.9.0-pf6/tools/objtool/objtool.o := gcc -Wp,-MD,/usr/src/linux-headers-5.9.0-pf6/tools/objtool/.objtool.o.d -Wp,-MT,/usr/src/linux-headers-5.9.0-pf6/tools/objtool/objtool.o -Werror -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wstrict-aliasing=3 -Wshadow -Wno-switch-default -Wno-switch-enum -Wno-packed -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89 -g -I/home/danila/Downloads/pf-kernel-v5.9-pf6/tools/include -I/home/danila/Downloads/pf-kernel-v5.9-pf6/tools/arch/x86/include/uapi -I/home/danila/Downloads/pf-kernel-v5.9-pf6/tools/arch/x86/include -I/home/danila/Downloads/pf-kernel-v5.9-pf6/tools/objtool/arch/x86/include -I/home/danila/Downloads/pf-kernel-v5.9-pf6/tools/lib -D"BUILD_STR(s)=$(pound)s" -c -o /usr/src/linux-headers-5.9.0-pf6/tools/objtool/objtool.o objtool.c

source_/usr/src/linux-headers-5.9.0-pf6/tools/objtool/objtool.o := objtool.c

deps_/usr/src/linux-headers-5.9.0-pf6/tools/objtool/objtool.o := \
  /usr/include/stdc-predef.h \
  /usr/include/stdio.h \
  /usr/include/bits/libc-header-start.h \
  /usr/include/features.h \
  /usr/include/sys/cdefs.h \
  /usr/include/bits/wordsize.h \
  /usr/include/bits/long-double.h \
  /usr/include/gnu/stubs.h \
  /usr/include/gnu/stubs-64.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/stddef.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/stdarg.h \
  /usr/include/bits/types.h \
  /usr/include/bits/timesize.h \
  /usr/include/bits/typesizes.h \
  /usr/include/bits/time64.h \
  /usr/include/bits/types/__fpos_t.h \
  /usr/include/bits/types/__mbstate_t.h \
  /usr/include/bits/types/__fpos64_t.h \
  /usr/include/bits/types/__FILE.h \
  /usr/include/bits/types/FILE.h \
  /usr/include/bits/types/struct_FILE.h \
  /usr/include/bits/stdio_lim.h \
  /usr/include/bits/floatn.h \
  /usr/include/bits/floatn-common.h \
  /usr/include/bits/stdio.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/stdbool.h \
  /usr/include/string.h \
  /usr/include/bits/types/locale_t.h \
  /usr/include/bits/types/__locale_t.h \
  /usr/include/strings.h \
  /usr/include/stdlib.h \
  /usr/include/bits/waitflags.h \
  /usr/include/bits/waitstatus.h \
  /usr/include/sys/types.h \
  /usr/include/bits/types/clock_t.h \
  /usr/include/bits/types/clockid_t.h \
  /usr/include/bits/types/time_t.h \
  /usr/include/bits/types/timer_t.h \
  /usr/include/bits/stdint-intn.h \
  /usr/include/endian.h \
  /usr/include/bits/endian.h \
  /usr/include/bits/endianness.h \
  /usr/include/bits/byteswap.h \
  /usr/include/bits/uintn-identity.h \
  /usr/include/sys/select.h \
  /usr/include/bits/select.h \
  /usr/include/bits/types/sigset_t.h \
  /usr/include/bits/types/__sigset_t.h \
  /usr/include/bits/types/struct_timeval.h \
  /usr/include/bits/types/struct_timespec.h \
  /usr/include/bits/pthreadtypes.h \
  /usr/include/bits/thread-shared-types.h \
  /usr/include/bits/pthreadtypes-arch.h \
  /usr/include/bits/struct_mutex.h \
  /usr/include/bits/struct_rwlock.h \
  /usr/include/alloca.h \
  /usr/include/bits/stdlib-bsearch.h \
  /usr/include/bits/stdlib-float.h \
  /home/danila/Downloads/pf-kernel-v5.9-pf6/tools/lib/subcmd/exec-cmd.h \
  /home/danila/Downloads/pf-kernel-v5.9-pf6/tools/lib/subcmd/pager.h \
  /home/danila/Downloads/pf-kernel-v5.9-pf6/tools/include/linux/kernel.h \
  /usr/include/assert.h \
  /home/danila/Downloads/pf-kernel-v5.9-pf6/tools/include/linux/build_bug.h \
  /home/danila/Downloads/pf-kernel-v5.9-pf6/tools/include/linux/compiler.h \
  /home/danila/Downloads/pf-kernel-v5.9-pf6/tools/include/linux/compiler-gcc.h \
  /home/danila/Downloads/pf-kernel-v5.9-pf6/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/bits/wchar.h \
  /usr/include/bits/stdint-uintn.h \
  /usr/include/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /home/danila/Downloads/pf-kernel-v5.9-pf6/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /home/danila/Downloads/pf-kernel-v5.9-pf6/tools/include/asm-generic/bitsperlong.h \
  /home/danila/Downloads/pf-kernel-v5.9-pf6/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/asm/posix_types.h \
  /usr/include/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /usr/include/byteswap.h \
  builtin.h \
  /home/danila/Downloads/pf-kernel-v5.9-pf6/tools/lib/subcmd/parse-options.h \

/usr/src/linux-headers-5.9.0-pf6/tools/objtool/objtool.o: $(deps_/usr/src/linux-headers-5.9.0-pf6/tools/objtool/objtool.o)

$(deps_/usr/src/linux-headers-5.9.0-pf6/tools/objtool/objtool.o):
